[package]
name = "nobject-rs"
version = "0.1.0"
authors = ["shmapdy <richard.meester@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99"
nom = "6.1.2"
thiserror = "1.0"